import type { Lang } from '@/lib/i18n';

// Every word the Sales Gallery shows, apart from the residences themselves (content/projects).
const en = {
 brand: 'Residences', allDemos: 'Residences — all demos',
 views: { 'five-room': '5 rooms', 'four-room': '4 rooms', garden: 'Garden', compact: 'Compact' },
 noneAvailable: 'None available right now',
 viewsLabel: 'Apartment types',
 tabs: { plan: 'Floor plan', film: 'Film', images: 'Images', model: '3D', about: 'About' },
 homePreview: 'Home preview',
 exploreBuilding: 'Explore the building', show: 'Show', building: 'Building', homeDetails: 'Home details', details: 'Details', selectedHome: 'Selected home',
 available: 'Available', sold: 'Sold', forSale: 'For sale',
 stepInside: 'Step inside', stepInsideLabel: 'Step inside: open the apartment view', stepInsideTitle: 'Plan, film, images and 3D, full screen',
 backToBuilding: 'Back to the building', returnToBuilding: 'Return to building', backToBuildingTitle: 'Back to the building (Esc)',
 downloadAssets: 'Download apartment assets (ZIP)',
 contactFor: (home: string) => `Contact the agent about ${home}`, whatsapp: 'WhatsApp', call: 'Call', email: 'Email',
 whatsappAbout: (home: string) => `Message on WhatsApp about ${home}`, callAgent: (name: string, phone: string) => `Call ${name}, ${phone}`, emailAbout: (home: string) => `Email about ${home}`,
 enquiryText: (project: string, home: string) => `Hello, I'd like details about ${home} at ${project}.`,
 homeRef: (number: number | undefined, where: string, home: string) => `${number ? `apartment ${number}, ` : ''}${where}, ${home}`,
 rooms: 'Rooms', floor: 'Floor', interior: 'Area', outdoor: 'Outdoor', sqm: 'm²', price: 'Price', currency: '₪',
 onRequest: 'On request', pricesOnRequest: 'On request from the sales office',
 interiorTitle: 'Listed area, including the private storage room',
 aptNo: (n: number) => `Apt. ${n}`,
 specs: { exposure: 'Exposure', parking: 'Parking', storage: 'Storage room', moveIn: 'Expected move-in' },
 parkingShort: 'Standard, underground', storageShort: 'Private, in the listed area',
 aboutSections: ['The layout', 'Worth checking'], homeFacts: 'Home details',
 // project info
 projectTab: 'Project', projectLabel: 'The project and its location', address: 'Address', buildingFacts: 'Building', floorsN: (n: number) => `${n} floors`,
 moveIn: 'Expected move-in', parking: 'Parking', storage: 'Storage', availabilityNow: 'Availability', homesAvailable: (n: number) => n === 1 ? '1 home available' : `${n} homes available`,
 prices: 'Prices', priceFrom: (p: string) => `From ${p}`, locationTitle: 'The location', mapTitle: (place: string) => `Map of ${place}`,
 openMaps: 'Google Maps', openWaze: 'Waze', addressTitle: 'The project, its location and a map', highlights: 'Project highlights', salesAgent: 'Sales agent',
 groundFloor: 'Ground floor', ground: 'Ground', groundShort: 'G',
 floorN: (n: number) => `Floor ${n}`,
 floorPlanOf: (home: string) => `${home} floor plan`,
 // picker
 chooseHome: 'Choose a home', availableHomes: (n: number) => n === 1 ? '1 available home' : `${n} available homes`, availableOf: (n: number, total: number) => `${n} of ${total} available`,
 pickerLabel: (summary: string) => `Choose an apartment. Selected: ${summary}`, byFloor: 'Apartments by floor',
 roomsCount: (n: number) => `${n} rooms`,
 // stage
 stageLabel: 'Building, 360°. Drag or use the left and right arrow keys to turn it.', architectLabel: 'Architect’s view of the building',
 angle: (n: number, total: number) => `Building, angle ${n} of ${total}`, availability: 'Apartment availability',
 facadeForSale: 'FOR SALE', facadeSold: 'SOLD',
 architectImage: 'Architect’s visualisation of the building',
 preparing: 'Preparing the building', failed: 'This view couldn’t load.', openArchitect: 'Open the architect’s view',
 showOnBuilding: 'Show on the building',
 toggle: (on: boolean, label: string) => `${on ? 'Hide' : 'Show'} ${label.toLowerCase()} on the building`,
 viewpoint: 'Viewpoint', front: 'Front', rear: 'Rear',
 hintTouch: 'Drag to turn the building, tap a floor to choose', hintMouse: 'Drag to turn the building, hover a floor to explore',
 turnLeft: 'Turn left', turnRight: 'Turn right',
 presentation: 'Building presentation', turnBuilding: 'Turn the building', architectView: 'Architect’s view',
 // media
 openPlan: (home: string) => `Open the ${home} floor plan full screen`,
 comingSoon: { film: 'The walkthrough film is in production', images: 'Interior images are in production', model: 'The 3D model is in production' }, comingSoonTag: 'Coming soon',
 sampleFilm: 'Sample film from another home', sampleImages: 'Sample imagery from another home', sampleModel: 'Sample model from another home',
 playFilm: 'Play the film', previousImage: 'Previous image', nextImage: 'Next image', images: 'Images',
 imageOf: (n: number, total: number) => `${n} of ${total}`, showImage: (label: string) => `Show ${label}`,
 aboutHome: (home: string) => `About the ${home.toLowerCase()}`,
 // lightbox
 zoomOut: 'Zoom out', zoomIn: 'Zoom in', fit: 'Fit to screen', close: 'Close',
 lightboxHint: 'Scroll or pinch to zoom · drag to move · double-click for a closer look',
 // 3D model
 modelAlt: 'Rotatable furnished cutaway of the apartment', preparingModel: 'Preparing the 3D model', modelFailed: 'The 3D model can’t be shown on this device.',
 modelView: 'Model view', modelLeft: 'Turn the model left', modelRight: 'Turn the model right', model3d: '3D', modelTop: 'Top', modelOutdoor: 'Outdoor', resetView: 'Reset the view', modelFloors: 'Floors',
};

export type ExplorerText = typeof en;

const he: ExplorerText = {
 brand: 'Residences', allDemos: 'Residences — כל ההדגמות',
 views: { 'five-room': '5 חדרים', 'four-room': '4 חדרים', garden: 'גן', compact: 'קומפקטית' },
 noneAvailable: 'אין דירות זמינות כרגע',
 viewsLabel: 'סוגי הדירות',
 tabs: { plan: 'תוכנית', film: 'סרטון', images: 'תמונות', model: 'תלת־ממד', about: 'על הדירה' },
 homePreview: 'תצוגת הדירה',
 exploreBuilding: 'סיור בבניין', show: 'הצגה', building: 'הבניין', homeDetails: 'פרטי הדירה', details: 'פרטים', selectedHome: 'הדירה שנבחרה',
 available: 'זמינה', sold: 'נמכרו', forSale: 'למכירה',
 stepInside: 'כניסה לדירה', stepInsideLabel: 'כניסה לדירה: תצוגת דירה במסך מלא', stepInsideTitle: 'תוכנית, סרטון, תמונות ותלת־ממד במסך מלא',
 backToBuilding: 'חזרה לבניין', returnToBuilding: 'חזרה לבניין', backToBuildingTitle: 'חזרה לבניין (Esc)',
 downloadAssets: 'הורדת קובצי הדירה (ZIP)',
 contactFor: home => `יצירת קשר עם הסוכן לגבי ${home}`, whatsapp: 'וואטסאפ', call: 'שיחה', email: 'אימייל',
 whatsappAbout: home => `הודעת וואטסאפ לגבי ${home}`, callAgent: (name, phone) => `שיחה עם ${name}, ${phone}`, emailAbout: home => `אימייל לגבי ${home}`,
 enquiryText: (project, home) => `שלום, אשמח לקבל פרטים על ${home} בפרויקט ${project}.`,
 homeRef: (number, where, home) => `${number ? `דירה ${number}, ` : ''}${where}, ${home}`,
 rooms: 'חדרים', floor: 'קומה', interior: 'שטח', outdoor: 'שטח חוץ', sqm: 'מ״ר', price: 'מחיר', currency: '₪',
 onRequest: 'לפי בקשה', pricesOnRequest: 'לפי בקשה ממשרד המכירות',
 interiorTitle: 'השטח המצוין, כולל מחסן דירתי',
 aptNo: n => `דירה ${n}`,
 specs: { exposure: 'כיווני אוויר', parking: 'חניה', storage: 'מחסן', moveIn: 'אכלוס צפוי' },
 parkingShort: 'תת קרקעית רגילה', storageShort: 'מחסן דירתי, כלול בשטח',
 aboutSections: ['תכנון הדירה', 'כדאי לבדוק'], homeFacts: 'פרטי הדירה',
 projectTab: 'הפרויקט', projectLabel: 'הפרויקט והמיקום', address: 'כתובת', buildingFacts: 'הבניין', floorsN: n => `${n} קומות`,
 moveIn: 'אכלוס צפוי', parking: 'חניה', storage: 'מחסן', availabilityNow: 'זמינות', homesAvailable: n => n === 1 ? 'דירה אחת זמינה' : `${n} דירות זמינות`,
 prices: 'מחירים', priceFrom: p => `החל מ־${p}`, locationTitle: 'המיקום', mapTitle: place => `מפה של ${place}`,
 openMaps: 'Google Maps', openWaze: 'Waze', addressTitle: 'הפרויקט, המיקום ומפה', highlights: 'עיקרי הפרויקט', salesAgent: 'סוכן המכירות',
 groundFloor: 'קומת קרקע', ground: 'קרקע', groundShort: 'ק',
 floorN: n => `קומה ${n}`,
 floorPlanOf: home => `תוכנית ${home}`,
 chooseHome: 'בחרו דירה', availableHomes: n => n === 1 ? 'דירה אחת זמינה' : `${n} דירות זמינות`, availableOf: (n, total) => `${n} מתוך ${total} זמינות`,
 pickerLabel: summary => `בחירת דירה. נבחרה: ${summary}`, byFloor: 'הדירות לפי קומה',
 roomsCount: n => `${n} חדרים`,
 stageLabel: 'הבניין ב־360°. גררו או השתמשו בחצים ימינה ושמאלה כדי לסובב אותו.', architectLabel: 'מבט אדריכלי על הבניין',
 angle: (n, total) => `הבניין, זווית ${n} מתוך ${total}`, availability: 'זמינות הדירות',
 facadeForSale: 'למכירה', facadeSold: 'נמכר',
 architectImage: 'הדמיית האדריכל של הבניין',
 preparing: 'הבניין נטען', failed: 'התצוגה לא נטענה.', openArchitect: 'למבט האדריכלי',
 showOnBuilding: 'הצגה על הבניין',
 toggle: (on, label) => `${on ? 'הסתרת' : 'הצגת'} הסימון „${label}” על הבניין`,
 viewpoint: 'נקודת מבט', front: 'חזית', rear: 'עורף',
 hintTouch: 'גררו כדי לסובב את הבניין, הקישו על קומה כדי לבחור', hintMouse: 'גררו כדי לסובב את הבניין, רחפו מעל קומה כדי לגלות',
 turnLeft: 'סיבוב שמאלה', turnRight: 'סיבוב ימינה',
 presentation: 'תצוגת הבניין', turnBuilding: 'סיבוב הבניין', architectView: 'מבט אדריכלי',
 openPlan: home => `פתיחת תוכנית ${home} במסך מלא`,
 comingSoon: { film: 'סרטון הסיור בהפקה', images: 'תמונות הפנים בהפקה', model: 'מודל התלת־ממד בהפקה' }, comingSoonTag: 'בקרוב',
 sampleFilm: 'סרטון לדוגמה מדירה אחרת', sampleImages: 'תמונות לדוגמה מדירה אחרת', sampleModel: 'מודל לדוגמה מדירה אחרת',
 playFilm: 'הפעלת הסרטון', previousImage: 'התמונה הקודמת', nextImage: 'התמונה הבאה', images: 'תמונות',
 imageOf: (n, total) => `${n} מתוך ${total}`, showImage: label => `הצגת ${label}`,
 aboutHome: home => `על ${home}`,
 zoomOut: 'הקטנה', zoomIn: 'הגדלה', fit: 'התאמה למסך', close: 'סגירה',
 lightboxHint: 'גללו או צבטו כדי להגדיל · גררו כדי להזיז · לחיצה כפולה למבט מקרוב',
 modelAlt: 'מודל מרוהט של הדירה בחתך, לסיבוב', preparingModel: 'מודל התלת־ממד נטען', modelFailed: 'לא ניתן להציג את מודל התלת־ממד במכשיר הזה.',
 modelView: 'תצוגת המודל', modelLeft: 'סיבוב המודל שמאלה', modelRight: 'סיבוב המודל ימינה', model3d: 'תלת־ממד', modelTop: 'מלמעלה', modelOutdoor: 'חוץ', resetView: 'איפוס התצוגה', modelFloors: 'קומות',
};

export const explorerText: Record<Lang, ExplorerText> = { en, he };
