import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
await fs.mkdir('review', { recursive: true });
const executablePath = process.env.CHROME_PATH || (process.platform === 'darwin' ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' : undefined);
const browser=await chromium.launch({executablePath,headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3088',{waitUntil:'networkidle'});
await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(img=>{img.loading='eager';return img.decode();})));
await page.screenshot({path:'review/desktop.png',fullPage:true});
await page.getByRole('button',{name:'Explore all 8 images'}).click();
await page.locator('dialog').waitFor({state:'visible'});
for(let i=0;i<8;i++){await page.locator('.lightbox-image').evaluate(img=>img.decode());await page.getByRole('button',{name:'Next image'}).click();}
await page.keyboard.press('Escape');
await page.locator('.hero-play').click();
await page.locator('video').evaluate(v=>new Promise(resolve=>{if(v.readyState>=1)resolve();else v.addEventListener('loadedmetadata',resolve,{once:true});}));
const duration=await page.locator('video').evaluate(v=>v.duration);
if(Math.abs(duration-20)>.1)throw new Error('Incorrect film duration '+duration);
await page.keyboard.press('Escape');
await page.locator('.viewer-preview').click();
await page.waitForFunction(()=>document.querySelector('model-viewer')?.loaded,{timeout:60000});
await page.locator('.viewer-shell').screenshot({path:'review/model.png'});
const before=await page.locator('model-viewer').evaluate(e=>e.getCameraOrbit().toString());
await page.getByRole('button',{name:'Plan view',exact:true}).click();
await page.waitForTimeout(1000);
const after=await page.locator('model-viewer').evaluate(e=>e.getCameraOrbit().toString());
if(before===after)throw new Error('Camera controls did not change model view');
await page.getByRole('button',{name:'Terrace',exact:true}).click();
await page.waitForTimeout(1000);
await page.locator('.viewer-shell').screenshot({path:'review/terrace-model.png'});
const box=await page.locator('model-viewer').boundingBox();
const preDrag=await page.locator('model-viewer').evaluate(e=>e.getCameraOrbit().toString());
await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+140,box.y+box.height/2+20,{steps:15});await page.mouse.up();await page.waitForTimeout(500);
if(preDrag===await page.locator('model-viewer').evaluate(e=>e.getCameraOrbit().toString()))throw new Error('Model drag failed');
await page.setViewportSize({width:390,height:844});
await page.goto('http://localhost:3088',{waitUntil:'networkidle'});
await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(img=>{img.loading='eager';return img.decode();})));
await page.screenshot({path:'review/mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
if(overflow)throw new Error('Mobile horizontal overflow');
await page.getByRole('button',{name:'Toggle navigation'}).click();
await page.getByRole('navigation').getByRole('link',{name:'The spaces'}).click();
if(await page.getByRole('button',{name:'Toggle navigation'}).getAttribute('aria-expanded')!=='false')throw new Error('Mobile menu did not close');
await page.getByRole('button',{name:'Explore all 8 images'}).click();
await page.locator('dialog').screenshot({path:'review/mobile-gallery.png'});
await page.keyboard.press('Escape');
await page.locator('.viewer-preview').click();
await page.waitForFunction(()=>document.querySelector('model-viewer')?.loaded,{timeout:60000});
await page.locator('.viewer-shell').screenshot({path:'review/mobile-model.png'});
await fs.writeFile('review/checks.json',JSON.stringify({desktop:'1440x1000',mobile:'390x844',filmDuration:duration,galleryImages:8,modelLoaded:true,cameraControls:true,mobileOverflow:overflow,errors},null,2));
await browser.close();
if(errors.length)throw new Error(errors.join('\n'));
console.log('Website checks passed: desktop, mobile, eight-image gallery, 20s film, GLB loading and view controls.');
