import type { Lang } from '@/lib/i18n';

// Every word on the Mozir 8 site. In headings, "\n" is a line break and *…* the italic accent.
type Room = { title: string; room: string; description: string };

const en = {
 skip: 'Skip to residence', home: 'Mozir 8 home', wordmarkNote: 'TEL AVIV RESIDENCES',
 nav: [['The residence', '#residence'], ['The spaces', '#spaces'], ['Explore in 3D', '#explore'], ['The address', '#address']] as [string, string][],
 navLabel: 'Main navigation', toggleNav: 'Toggle navigation', menu: 'Menu', close: 'Close', watchFilm: 'Watch the film',
 heroAlt: 'Sunlit proposed living room opening onto the garden terrace',
 heroTop: ['8 YAAKOV MOZIR · TEL AVIV', 'THE GARDEN RESIDENCE / 02'],
 heroEyebrow: 'A QUIETER KIND OF CITY LIVING', heroTitle: 'A little more\nroom to *live.*', heroText: 'Open space. Soft light. Your own corner of Tel Aviv.',
 heroLink: 'Discover the residence', heroPlay: 'Step inside', heroPlayNote: 'THE RESIDENCE FILM · 20 SEC', heroDisclaimer: 'Illustrative interior concept',
 residenceEyebrow: '01 / THE RESIDENCE', residenceLabel: 'GROUND FLOOR · APARTMENT 02', residenceTitle: 'City on the outside.\n*Sanctuary within.*',
 residenceText: ['A home with space to breathe, at 8 Yaakov Mozir. Two bedrooms, open living and dining, and a wraparound garden terrace bring a different rhythm to life in Tel Aviv.', 'Our interior concept pairs natural textures and warm neutrals with the easy openness of contemporary Israeli living.'],
 originalPlan: 'View the original floor plan',
 specs: [['85.5', 'M² · APPROX. INTERIOR'], ['02', 'BEDROOMS'], ['02', 'BATHROOMS'], ['Garden', 'WRAPAROUND OUTDOOR SPACE']] as [string, string][],
 filmAlt: 'Proposed terrace design with outdoor seating and an illustrative Israeli neighborhood outlook',
 filmEyebrow: '20 SECONDS. A DIFFERENT PACE.', filmTitle: 'Feel what it’s like\nto *come home.*', filmPlay: 'Play the residence film with jazz-fusion soundtrack',
 filmBottom: ['THE RESIDENCE FILM', 'WITH SOUND · 00:20'],
 spacesEyebrow: '02 / THE SPACES', spacesLabel: 'AN INTERIOR VISION', spacesTitle: 'Considered details.\n*Unhurried living.*', spacesText: 'Explore the residence, room by room.\nA warm, tactile vision of home.',
 imageAlt: (room: string) => `${room} — proposed interior design`, galleryBottom: 'From intimate corners to open-air moments.', allImages: 'Explore all 8 images',
 exploreEyebrow: '03 / A NEW PERSPECTIVE', exploreLabel: 'YOUR PRIVATE 3D VIEWING', exploreTitle: 'Make yourself\n*at home.*', exploreText: 'Turn the apartment. Explore the layout.\nSee how each space connects to the next.',
 openPlan: 'Open floor plan', previewAlt: 'Illustrative overhead view of the apartment and terrace', exploreStart: 'Explore the apartment in 3D', exploreStartNote: 'ROTATE · ZOOM · DISCOVER',
 modelNoteTag: 'THE FULL APARTMENT. INCLUDING THE TERRACE.', modelNote: 'Plan-based 3D layout with illustrative furniture and simplified finishes. Images show the proposed interior styling.',
 terraceAlt: 'Full terrace concept with a dining table, lounge seating and planting', terraceEyebrow: 'THE OUTDOOR ROOM', terraceTitle: 'A table for friends.\nA moment\n*for yourself.*',
 terraceText: 'Doors slide open. The living space flows out. The wraparound terrace becomes another room—one with a little more sky.', closerLook: 'Take a closer look', terraceNote: 'Outdoor design and neighborhood view are illustrative.',
 addressEyebrow: '04 / THE ADDRESS', addressTitle: 'Tel Aviv,\n*at your pace.*', address: '8 Yaakov Mozir', addressOther: { text: 'יעקב מוזיר 8, תל אביב', lang: 'he' },
 addressText: 'In Tel Aviv’s New North, in the Kikar HaMedina area. A residential setting with the city as your backdrop.', neighborhood: 'Explore the neighborhood',
 developerEyebrow: 'THE PROJECT', developer: 'Urban Real Estate', developerText: 'Urban Real Estate works in residential development and urban renewal. The company is listed as the developer of the Yaakov Mozir 8 project.',
 projectLink: 'Project & enquiry details', buildingAlt: 'Supplied architectural marketing image of the building at Mozir 8', buildingCaption: 'MOZIR 8 · BUILDING VISUALIZATION',
 closingEyebrow: 'THE GARDEN RESIDENCE · MOZIR 8', closingTitle: 'More space.\n*More possibility.*', closingCta: 'Enquire about the project', closingLine: 'Apartment 02 · 8 Yaakov Mozir, Tel Aviv',
 floorPlan: 'Floor plan', allDemos: 'All demos', backToTop: 'Back to top',
 disclaimer: 'A visual introduction to Apartment 02. AI-generated images and film illustrate a proposed interior; furniture, finishes, landscaping and exterior views are not a specification or a verified view. Approximate area is taken from the supplied sales plan. Confirm all property details and availability with the project representative.',
 sourcesTitle: 'Project information & sources', sources: ['Supplied apartment sales plan (Mozir 8 Tel Aviv Ltd.)', 'Yad2 project listing — developer and location', 'Urban Real Estate — company information'], concept: 'Presentation concept · September 2026',
 filmDialog: 'The residence film', galleryDialog: 'Residence image gallery', closeViewer: 'Close viewer', filmMeta: '20 SEC · JAZZ FUSION', illustrative: (room: string) => `${room} — illustrative design`,
 previousImage: 'Previous image', nextImage: 'Next image',
 rooms: [
  { title: 'Room to come together', room: 'Living & dining', description: 'An open living space, framed by warm materials and a generous connection to the outdoors.' },
  { title: 'A slower start', room: 'Principal bedroom', description: 'A private retreat with a calm palette and its own adjoining bathroom.' },
  { title: 'Everyday rituals', room: 'En suite', description: 'Natural tones and pared-back detailing in the proposed private bathroom.' },
  { title: 'Space for possibility', room: 'Second bedroom', description: 'A flexible second bedroom, imagined with the same quiet attention to detail.' },
  { title: 'Quietly considered', room: 'Main bathroom', description: 'An airy, carefully composed interpretation of the main bathroom.' },
  { title: 'The heart of the home', room: 'Kitchen', description: 'Soft cabinetry, tactile surfaces and an easy connection to the living and dining spaces.' },
  { title: 'See the whole picture', room: 'The complete residence', description: 'An illustrative overview of the apartment and its wraparound outdoor space.' },
  { title: 'Life, a little more open', room: 'Garden terrace', description: 'An outdoor room for long lunches, slow mornings and a little space to yourself.' },
 ] as Room[],
 viewer: {
  alt: 'Rotatable furnished cutaway of Apartment 02, including the full wraparound terrace', loading: 'Preparing your private viewing…', failed: 'The 3D viewer could not load on this device.',
  planLink: 'View the apartment plan', tag: 'APARTMENT 02 / INTERACTIVE MODEL', views: { perspective: 'Perspective', plan: 'Plan view', terrace: 'Terrace' }, compact: { perspective: '3D', plan: 'Plan', terrace: 'Terrace' },
  reset: 'Reset apartment view', rotate: 'Drag to rotate', zoom: 'Scroll or pinch to zoom',
 },
};

export type MozirText = typeof en;

const he: MozirText = {
 skip: 'דלגו לדירה', home: 'מוזיר 8, דף הבית', wordmarkNote: 'דירות בתל אביב',
 nav: [['הדירה', '#residence'], ['החללים', '#spaces'], ['סיור בתלת־ממד', '#explore'], ['הכתובת', '#address']],
 navLabel: 'ניווט ראשי', toggleNav: 'פתיחה וסגירה של הניווט', menu: 'תפריט', close: 'סגירה', watchFilm: 'לצפייה בסרטון',
 heroAlt: 'סלון מואר בשמש עם יציאה למרפסת הגן, בעיצוב מוצע',
 heroTop: ['יעקב מוזיר 8 · תל אביב', 'דירת הגן / 02'],
 heroEyebrow: 'חיים בעיר, בקצב שקט יותר', heroTitle: 'קצת יותר\nמקום *לחיות.*', heroText: 'מרחב פתוח. אור רך. פינה משלכם בתל אביב.',
 heroLink: 'לגלות את הדירה', heroPlay: 'היכנסו פנימה', heroPlayNote: 'סרטון הדירה · 20 שניות', heroDisclaimer: 'הדמיה של עיצוב פנים מוצע',
 residenceEyebrow: '01 / הדירה', residenceLabel: 'קומת קרקע · דירה 02', residenceTitle: 'בחוץ, העיר.\n*בפנים, מפלט.*',
 residenceText: ['בית עם מקום לנשום, ברחוב יעקב מוזיר 8. שני חדרי שינה, סלון ופינת אוכל פתוחים ומרפסת גן שמקיפה את הדירה מביאים קצב אחר לחיים בתל אביב.', 'קונספט העיצוב שלנו משלב טקסטורות טבעיות וגוונים חמים ורכים עם הפתיחות הקלילה של המגורים הישראליים העכשוויים.'],
 originalPlan: 'לתוכנית הדירה המקורית',
 specs: [['85.5', 'מ״ר · שטח פנימי בקירוב'], ['02', 'חדרי שינה'], ['02', 'חדרי רחצה'], ['גינה', 'שטח חוץ שמקיף את הדירה']],
 filmAlt: 'עיצוב מוצע למרפסת עם פינת ישיבה ונוף שכונתי להמחשה',
 filmEyebrow: '20 שניות. קצב אחר.', filmTitle: 'להרגיש איך זה\n*לחזור הביתה.*', filmPlay: 'הפעלת סרטון הדירה עם פסקול ג׳אז־פיוז׳ן',
 filmBottom: ['סרטון הדירה', 'עם סאונד · 00:20'],
 spacesEyebrow: '02 / החללים', spacesLabel: 'חזון לעיצוב הפנים', spacesTitle: 'פרטים מדויקים.\n*חיים בלי למהר.*', spacesText: 'סיור בדירה, חדר אחר חדר.\nחזון חם ומוחשי של בית.',
 imageAlt: room => `${room} — עיצוב פנים מוצע`, galleryBottom: 'מפינות אינטימיות ועד רגעים באוויר הפתוח.', allImages: 'לכל 8 התמונות',
 exploreEyebrow: '03 / נקודת מבט חדשה', exploreLabel: 'סיור פרטי בתלת־ממד', exploreTitle: 'תרגישו\n*בבית.*', exploreText: 'סובבו את הדירה. גלו את החלוקה.\nראו איך כל חלל מתחבר לבא אחריו.',
 openPlan: 'לתוכנית הדירה', previewAlt: 'מבט על להמחשה של הדירה והמרפסת', exploreStart: 'לסיור בדירה בתלת־ממד', exploreStartNote: 'סיבוב · זום · גילוי',
 modelNoteTag: 'הדירה כולה. כולל המרפסת.', modelNote: 'מודל תלת־ממד לפי התוכנית, עם ריהוט להמחשה וגימורים מפושטים. התמונות מציגות את עיצוב הפנים המוצע.',
 terraceAlt: 'קונספט למרפסת המלאה עם שולחן אוכל, פינת ישיבה וצמחייה', terraceEyebrow: 'החדר שבחוץ', terraceTitle: 'שולחן לחברים.\nרגע\n*לעצמכם.*',
 terraceText: 'הדלתות נפתחות. הסלון זורם החוצה. המרפסת המקיפה הופכת לעוד חדר — עם קצת יותר שמיים.', closerLook: 'למבט מקרוב', terraceNote: 'עיצוב החוץ והנוף השכונתי הם להמחשה בלבד.',
 addressEyebrow: '04 / הכתובת', addressTitle: 'תל אביב,\n*בקצב שלכם.*', address: 'יעקב מוזיר 8, תל אביב', addressOther: { text: '8 Yaakov Mozir, Tel Aviv', lang: 'en' },
 addressText: 'בצפון החדש של תל אביב, באזור כיכר המדינה. סביבת מגורים, עם העיר כתפאורה.', neighborhood: 'לגלות את השכונה',
 developerEyebrow: 'הפרויקט', developer: 'אורבן נדל״ן', developerText: 'אורבן נדל״ן עוסקת בייזום מגורים ובהתחדשות עירונית. החברה רשומה כיזמית פרויקט יעקב מוזיר 8.',
 projectLink: 'פרטי הפרויקט ויצירת קשר', buildingAlt: 'הדמיה שיווקית אדריכלית של הבניין במוזיר 8', buildingCaption: 'מוזיר 8 · הדמיית הבניין',
 closingEyebrow: 'דירת הגן · מוזיר 8', closingTitle: 'יותר מקום.\n*יותר אפשרויות.*', closingCta: 'לפרטים על הפרויקט', closingLine: 'דירה 02 · יעקב מוזיר 8, תל אביב',
 floorPlan: 'תוכנית הדירה', allDemos: 'כל ההדגמות', backToTop: 'חזרה למעלה',
 disclaimer: 'היכרות חזותית עם דירה 02. התמונות והסרטון נוצרו בבינה מלאכותית ומדגימים עיצוב פנים מוצע; הריהוט, הגימורים, הגינון והנופים אינם מפרט ואינם נוף מאומת. השטח המשוער לקוח מתוכנית המכירה שסופקה. יש לאמת את כל פרטי הנכס והזמינות מול נציג הפרויקט.',
 sourcesTitle: 'מידע על הפרויקט ומקורות', sources: ['תוכנית המכירה של הדירה (מוזיר 8 תל אביב בע״מ)', 'דף הפרויקט ביד2 — יזם ומיקום', 'אורבן נדל״ן — מידע על החברה'], concept: 'קונספט להצגה · ספטמבר 2026',
 filmDialog: 'סרטון הדירה', galleryDialog: 'גלריית התמונות של הדירה', closeViewer: 'סגירה', filmMeta: '20 שניות · ג׳אז־פיוז׳ן', illustrative: room => `${room} — עיצוב להמחשה`,
 previousImage: 'התמונה הקודמת', nextImage: 'התמונה הבאה',
 rooms: [
  { title: 'מקום להתכנס', room: 'סלון ופינת אוכל', description: 'חלל מגורים פתוח, עטוף בחומרים חמים ובחיבור נדיב לחוץ.' },
  { title: 'בוקר איטי יותר', room: 'חדר השינה הראשי', description: 'מפלט פרטי בפלטה רגועה, עם חדר רחצה צמוד.' },
  { title: 'טקסים של יום־יום', room: 'חדר רחצה צמוד', description: 'גוונים טבעיים ופרטים מינימליים בחדר הרחצה הפרטי המוצע.' },
  { title: 'מקום לאפשרויות', room: 'חדר שינה שני', description: 'חדר שינה שני וגמיש, מעוצב באותה תשומת לב שקטה לפרטים.' },
  { title: 'שקט ומדויק', room: 'חדר הרחצה הראשי', description: 'פרשנות מאווררת ומוקפדת לחדר הרחצה הראשי.' },
  { title: 'לב הבית', room: 'מטבח', description: 'ארונות רכים, משטחים מוחשיים וחיבור קל לסלון ולפינת האוכל.' },
  { title: 'התמונה המלאה', room: 'הדירה כולה', description: 'מבט על להמחשה של הדירה ושל שטח החוץ שמקיף אותה.' },
  { title: 'חיים קצת יותר פתוחים', room: 'מרפסת הגן', description: 'חדר בחוץ לארוחות צהריים ארוכות, לבקרים איטיים ולקצת זמן לעצמכם.' },
 ],
 viewer: {
  alt: 'מודל מרוהט של דירה 02 בחתך, כולל מרפסת הגן המקיפה, לסיבוב', loading: 'הסיור הפרטי שלכם נטען…', failed: 'לא ניתן לטעון את מודל התלת־ממד במכשיר הזה.',
  planLink: 'לתוכנית הדירה', tag: 'דירה 02 / מודל אינטראקטיבי', views: { perspective: 'פרספקטיבה', plan: 'מבט על', terrace: 'מרפסת' }, compact: { perspective: 'תלת־ממד', plan: 'תוכנית', terrace: 'מרפסת' },
  reset: 'איפוס תצוגת הדירה', rotate: 'גררו כדי לסובב', zoom: 'גללו או צבטו כדי להגדיל',
 },
};

export const mozirText: Record<Lang, MozirText> = { en, he, pt: en };  // these pages offer Hebrew, not Portuguese (lib/i18n LANG_PAGES)
