import type { Lang } from '@/lib/i18n';
import type { Dir } from '@/content/projects/gindi';

const en = {
 brandLine: 'Gindi Holdings',
 contact: 'Contact',
 complex: 'The complex',
 building: 'Building',
 buildingN: (n: number) => `Building ${String(n).padStart(2, '0')}`,
 buildingShort: (n: number) => `0${n}`,
 residences: 'Residences',
 residencesN: (n: number) => `${n} residences`,
 availableN: (n: number) => `${n} available`,
 explore: 'Explore',
 chooseBuilding: 'Choose a building',
 heroKicker: 'Kiryat HaSharon · Netanya',
 heroLine: 'Four towers on the park. Choose a building, then a floor, then your home.',
 hintMouse: 'Drag to turn · click a building',
 hintTouch: 'Swipe to turn · tap a building',
 towerHint: 'Drag to turn · click a home on the facade',
 towerHintTouch: 'Swipe to turn · tap a home',
 turnLeft: 'Turn left', turnRight: 'Turn right',
 viewMode: 'How to see the complex', viewTowers: '3D towers', viewAerial: 'Whole complex', aerialAlt: 'The whole complex from the air: four towers on the park, the playground and the orchard', aerialCaption: 'Developer\'s aerial rendering',
 loading: 'Preparing the view',
 floor: 'Floor', floorN: (n: number) => n === 21 ? 'Penthouse floor 21' : `Floor ${n}`,
 floorShort: (n: number) => n === 21 ? 'PH' : String(n),
 all: 'All', rooms: 'rooms', roomsN: (n: number) => `${n} rooms`, penthouse: 'Penthouse', toCome: 'Plan to come',
 onlyAvailable: 'Available only',
 forSale: 'For sale', sold: 'Sold',
 back: 'All residences',
 interior: 'Interior', balcony: 'Balcony', terraces: 'Terraces', exposure: 'Aspect', price: 'Price', onRequest: 'On request',
 m2: (v: number) => `${v} m²`,
 plan: 'Plan', interiors: 'Interiors', film: 'Film', views: 'Views', position: 'On the floor',
 downloadPlan: 'Download plan (PDF)', downloadFiles: 'Download files', downloadFilesTitle: 'Download all of this home\'s files: plan, film, interiors and 3D (ZIP)', bookMeeting: 'Book a meeting',
 planToCome: 'The developer has not published this plan yet. Register your interest and the sales team will send it when it is ready.',
 illustrative: 'Illustrative', filmDraft: 'Walkthrough film · 1080p', model3d: '3D', openModel: 'Open the 3D model full screen', modelNote: 'Furnished study model: drag to turn, scroll or pinch to zoom.',
 viewsNote: 'Illustrative outlooks, generated for this demo from the surroundings; not photographs from the floor.',
 dir: { north: 'North', south: 'South', east: 'East', west: 'West' } as Record<Dir, string>,
 exposureText: (d: Dir[]) => d.map(x => en.dir[x]).join(' · '),
 statusText: (s: 'available' | 'sold'): string => s === 'available' ? 'For sale' : 'Sold',
 sampleNote: 'Sample availability — a demo, not the developer’s inventory.',
 soldNote: 'This home is sold. Similar homes in this building are marked in gold.',
 formTitle: 'Book a meeting', formLede: 'Leave your details and a Gindi representative will call you back.',
 formName: 'Full name', formPhone: 'Phone', formEmail: 'Email (optional)', formSend: 'Send', formAbout: 'About',
 formDone: 'Thank you. This is a demo, so nothing was sent — on the live site the sales team would call you back.',
 close: 'Close', openPlan: 'Enlarge plan',
 disclaimer: 'Demo. The towers are a study model built from the developer’s plans and renders; interiors and outlooks are illustrations; availability is invented. Binding details are those in the sale agreement.',
 unitTitle: (type: string, floor: number) => `${type} · ${floor === 21 ? 'Penthouse floor' : `Floor ${floor}`}`,
 matrix: 'Floor by floor',
 matrixNote: 'Each row is a floor; each tile a home.',
 visibleOther: 'Turning to show it…',
 notVisible: 'On the far side — turn the building to see it.',
 homeSelected: 'Selected home',
 stepInside: 'Step inside', backToBuilding: 'Back to building', stepInsideTitle: 'Give the home the whole screen: plan, film, interiors and 3D', backToBuildingTitle: 'Return to the building (Esc)',
 chooseHome: 'Choose a home', aboutTab: 'About', prevImage: 'Previous image', nextImage: 'Next image', floorsOfType: 'Where this type is',
};
export type GindiText = typeof en;

const he: GindiText = {
 brandLine: 'גינדי החזקות',
 contact: 'צור קשר',
 complex: 'המתחם',
 building: 'בניין',
 buildingN: (n: number) => `בניין ${String(n).padStart(2, '0')}`,
 buildingShort: (n: number) => `0${n}`,
 residences: 'דירות',
 residencesN: (n: number) => `${n} דירות`,
 availableN: (n: number) => `${n} למכירה`,
 explore: 'לבניין',
 chooseBuilding: 'בחרו בניין',
 heroKicker: 'קריית השרון · נתניה',
 heroLine: 'ארבעה מגדלים מול הפארק. בוחרים בניין, קומה — ואת הבית.',
 hintMouse: 'גררו לסיבוב · לחצו על בניין',
 hintTouch: 'החליקו לסיבוב · הקישו על בניין',
 towerHint: 'גררו לסיבוב · לחצו על דירה בחזית',
 towerHintTouch: 'החליקו לסיבוב · הקישו על דירה',
 turnLeft: 'סיבוב שמאלה', turnRight: 'סיבוב ימינה',
 viewMode: 'איך לראות את המתחם', viewTowers: 'מגדלים בתלת־ממד', viewAerial: 'המתחם כולו', aerialAlt: 'המתחם כולו ממבט אוויר: ארבעה מגדלים על הפארק, גן המשחקים והפרדס', aerialCaption: 'הדמיית אוויר של היזם',
 loading: 'מכינים את התצוגה',
 floor: 'קומה', floorN: (n: number) => n === 21 ? 'קומת הפנטהאוז 21' : `קומה ${n}`,
 floorShort: (n: number) => n === 21 ? 'PH' : String(n),
 all: 'הכל', rooms: 'חדרים', roomsN: (n: number) => `${n} חדרים`, penthouse: 'פנטהאוז', toCome: 'תוכנית בקרוב',
 onlyAvailable: 'רק למכירה',
 forSale: 'למכירה', sold: 'נמכרה',
 back: 'כל הדירות',
 interior: 'שטח דירה', balcony: 'מרפסת', terraces: 'מרפסות', exposure: 'כיווני אוויר', price: 'מחיר', onRequest: 'לפי פנייה',
 m2: (v: number) => `${v} מ״ר`,
 plan: 'תוכנית', interiors: 'הדמיות', film: 'סרטון', views: 'נוף', position: 'מיקום בקומה',
 downloadPlan: 'הורדת התוכנית (PDF)', downloadFiles: 'הורדת קבצים', downloadFilesTitle: 'הורדת כל קובצי הדירה: תוכנית, סרטון, הדמיות ותלת־ממד (ZIP)', bookMeeting: 'לתיאום פגישה',
 planToCome: 'היזם טרם פרסם את התוכנית הזו. השאירו פרטים וצוות המכירות ישלח אותה כשתהיה מוכנה.',
 illustrative: 'להמחשה', filmDraft: 'סרטון סיור · 1080p', model3d: 'תלת־ממד', openModel: 'פתיחת מודל התלת־ממד במסך מלא', modelNote: 'מודל עבודה מרוהט: גררו לסיבוב, גללו או צבטו לזום.',
 viewsNote: 'נופים להמחשה, שנוצרו להדגמה מתוך הסביבה; אינם צילומים מהקומה.',
 dir: { north: 'צפון', south: 'דרום', east: 'מזרח', west: 'מערב' },
 exposureText: (d: Dir[]) => d.map(x => he.dir[x]).join(' · '),
 statusText: (s: 'available' | 'sold') => s === 'available' ? 'למכירה' : 'נמכרה',
 sampleNote: 'זמינות לדוגמה — הדגמה, לא המלאי של היזם.',
 soldNote: 'הדירה נמכרה. דירות דומות בבניין מסומנות בזהב.',
 formTitle: 'תיאום פגישה', formLede: 'השאירו פרטים ונציג גינדי יחזור אליכם.',
 formName: 'שם מלא', formPhone: 'טלפון', formEmail: 'דוא״ל (לא חובה)', formSend: 'שליחה', formAbout: 'בנוגע ל',
 formDone: 'תודה. זוהי הדגמה ולכן דבר לא נשלח — באתר האמיתי צוות המכירות היה חוזר אליכם.',
 close: 'סגירה', openPlan: 'הגדלת התוכנית',
 disclaimer: 'הדגמה. המגדלים הם מודל עבודה שנבנה מתוכניות היזם והדמיותיו; העיצוב הפנימי והנופים הם המחשות; הזמינות בדויה. הנתונים המחייבים הם אלה שבהסכם המכר.',
 unitTitle: (type: string, floor: number) => `${type} · ${floor === 21 ? 'קומת הפנטהאוז' : `קומה ${floor}`}`,
 matrix: 'קומה אחר קומה',
 matrixNote: 'כל שורה היא קומה; כל אריח — דירה.',
 visibleOther: 'מסובבים כדי להראות אותה…',
 notVisible: 'בצד השני — סובבו את הבניין כדי לראות אותה.',
 homeSelected: 'הדירה שנבחרה',
 stepInside: 'היכנסו לדירה', backToBuilding: 'חזרה לבניין', stepInsideTitle: 'הדירה על כל המסך: תוכנית, סרטון, הדמיות ותלת־ממד', backToBuildingTitle: 'חזרה לבניין (Esc)',
 chooseHome: 'בחרו דירה', aboutTab: 'על הדירה', prevImage: 'התמונה הקודמת', nextImage: 'התמונה הבאה', floorsOfType: 'היכן נמצא הטיפוס',
};

export const gindiText: Record<Lang, GindiText> = { en, he };
